@startuml

package client #CCCCCC {
  class SpreadsheetController
  abstract class Client
  package text #EEEEEE {
    class TextClient
    class Command
  }
}

package visitors #CCCCCC{
  interface FormulaVisitor
  interface VisitedElem
  package visitors.impl #EEEEEE {
    class FormulaCalcVisitor
  }
}

package subscribers  #CCCCCC{
  interface Subscriber
  class CellDependencies
}

package util #CCCCCC {
  interface SpreadsheetLoader
  interface SpreadsheetSaver
  class S2VSpreadsheetLoader
  class S2VSpreadsheetSaver
  interface InputChecker
}

package model #CCCCCC {
  class Spreadsheet
  class Coordinate
  class Cell
  interface Content
  class NumericalContent
  class TextContent
  class FormulaContent
  interface Value
  class TextValue
  class NumericalValue
}

package operands #CCCCCC {
interface ExpressionComponent
interface Operator
interface Operand
interface Expression

  package operands.impl #EEEEEE {
    class CellsRange
    class PostFixExpression
    class AddOperator
    class SubsOperator
    class MultOperator
    class DivOperator
  }
}

package functions #CCCCCC {
  interface FunctionsRegister
  interface Function
  package functions.impl #EEEEEE {
    class FunctionsRegisterImpl
    class SumaFunction
    class PromedioFunction
    class MinFunction
    class MaxFunction
  }
}

package factories #CCCCCC {
  abstract SpreadsheetFactory
  package factories.impl #EEEEEE {
    class DefaultFactory
  }
}

package postfix #CCCCCC {
  interface Token
  interface Tokenizer
  interface SyntaxChecker
  interface PostFixGenerator
  package postfix.impl #EEEEEE {
    class TokenImpl
    class TokenizerImpl
    class SyntaxCheckerImpl
    class PostFixGeneratorImpl
    }
}

package view #CCCCCC {
  interface UIFactory
  interface UIRenderer
  interface UISpreadsheet
  package view.text #EEEEEE {
    class TextUIFactory
    class TextUIRenderer
    class TextUISpreadsheet
    }
}


/' ----- controller ----- '/
SpreadsheetController "1" --> "1" UISpreadsheet
SpreadsheetController --> "1" Spreadsheet

SpreadsheetController --> "1" SpreadsheetFactory
SpreadsheetController --> "1" UIFactory

SpreadsheetController --> "1" SpreadsheetLoader
SpreadsheetController --> "1" SpreadsheetSaver

Client --> "1" UIRenderer
Client --> "1" UISpreadsheet
Client --> "1" SpreadsheetController
Client --> InputChecker
Client <|-- TextClient

/' ----- view ----- '/
UIRenderer <|-- TextUIRenderer
UISpreadsheet <|-- TextUISpreadsheet
UIFactory <|-- TextUIFactory

/' ----- visitors ----- '/
FormulaCalcVisitor -up-|> FormulaVisitor
FormulaCalcVisitor --> Spreadsheet
FormulaVisitor <-- Coordinate

VisitedElem --> FormulaVisitor

Content --|> VisitedElem
Operand --|> VisitedElem


/' ----- subscribers ----- '/
Subscriber --> FormulaVisitor
CellDependencies --> Coordinate


/' ----- loading/saving ----- '/
SpreadsheetSaver <|-- S2VSpreadsheetSaver
SpreadsheetLoader <|-- S2VSpreadsheetLoader

SpreadsheetSaver ..> Spreadsheet
SpreadsheetLoader ..> Spreadsheet

/' ----- operands ----- '/
SpreadsheetFactory --> ExpressionComponent
Operator -up-|> ExpressionComponent
Operand -up-|> ExpressionComponent
Expression --|> Operand
Expression o--> "1..*" ExpressionComponent

NumericalValue -up-|> Operand
CellsRange -up-|> Operand
Coordinate --|> Operand
PostFixExpression -up-|>  Expression
AddOperator -up-|>  Operator
SubsOperator -up-|>  Operator
MultOperator -up-|>  Operator
DivOperator -up-|>  Operator

PostFixExpression --> FormulaVisitor
Number --> FormulaVisitor
Operator --> FormulaVisitor

CellsRange o--> "1..*" Coordinate


/' ----- model ----- '/
Spreadsheet --> "1" PostFixGenerator
Spreadsheet "1" -- "1" FormulaVisitor
Spreadsheet --> "0..*" CellDependencies
Spreadsheet --> "0..*" Cell

NumericalContent -up-|> Content
TextContent -up-|> Content
FormulaContent -right-|> Content
FormulaContent ..|> Subscriber
Content ..|> VisitedElem

NumericalContent --> "1" Number
FormulaContent --> "1" Expression

Value <|-- NumericalValue
Value <|-- TextValue

/' ----- functions ----- '/
SpreadsheetFactory --> FunctionsRegister
PostFixGenerator --> FunctionsRegister
FunctionsRegisterImpl -up-|> FunctionsRegister

Operand ..> FormulaVisitor
Function --|> Operand
SumaFunction -up-|> Function
MinFunction -up-|> Function
MaxFunction -up-|> Function
PromedioFunction -up-|> Function


/' ----- factories ----- '/

DefaultFactory -down-|> SpreadsheetFactory
SpreadsheetFactory --> Spreadsheet

/' ----- postfix ----- '/
SpreadsheetFactory -- PostFixGenerator
SpreadsheetFactory -- SyntaxChecker
SpreadsheetFactory -- Tokenizer
SpreadsheetFactory --> Token
PostFixGenerator --> SyntaxChecker
SyntaxChecker --> Tokenizer
Tokenizer --> Token
PostFixGeneratorImpl -up-|> PostFixGenerator
SyntaxCheckerImpl -up-|> SyntaxChecker
TokenizerImpl -up-|> Tokenizer
TokenImpl -up-|> Token

@enduml